<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

### 1.2 Subsetting by masking (Arrays only)

In [2]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
#subsetting only works with numpy arrays

[False False False  True  True  True  True  True  True  True]


### 1.3 Indexing & Slicing 2D Lists

In [3]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[np_array > 3]
np_array[~(np_array > 3)]                    # '~' means 'NOT'
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.4 Indexing & Slicing 2D Arrays

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[3]        # What is at position 4 (index 3)?
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
py_list_2d[:3]
py_list_2d[:3][0] #this gives the first [] in the list of 0-3

[1, 'A']

In [48]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
np_array_2d[3]       # What is at position 4 (index 3)?
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)
np_array_2d[:3]      #0 to 3 []
np_array_2d[3:6, 0]  #3 to 6 first element
#np_array_2d[:, 0]    #FIRST element of all []

array(['4', '5', '6'], dtype='<U11')

### 1.5 Growing lists

In [19]:
x=[1]*10
x               

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [20]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [21]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [22]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [23]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [24]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [25]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

#Cannot change/manipulate the data!

1


### 2.2 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x.copy()  #NOT y=x
z=x.copy()  #NOT z=x

## Exercise 1 :  Total recall?

|Term|Brief description|
|:---|:---------------:|
|Subsetting|Picking out certain elements at specific orders from a  array|
|Indexing|Selecting a certain element from a list or array|
|Slicing|Picking out a range of elements from list or array|
|Masking|Either creating a new variable that contains a subset of the original array or doing it directly|

## Exercise 2 :  Show me the ‘odd’ letters

In [55]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
e = np_array_2d[0:10, 0]
e = e.astype(int)
e %= 2
print(e)

mask = e == 1
print(mask)

np_array_2d[:2, 1], np_array_2d[4:6, 1] , np_array_2d[-1, 1]

    

[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]


(array(['A', 'C'], dtype='<U11'), array(['E', 'G'], dtype='<U11'), 'I')