<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [2]:
#python lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
#np arrays
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
#dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [4]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
print(py_super_names[-2])
#0,1,2
#-3,-2,-1

Iron Man


### 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Tony Stark"])
superhero_info.keys()
superhero_info.values()

Iron Man


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info[-3])

['Natasha Romanoff', 'Black Widow']


## 2 Lists vs. Arrays

### 2.1 Size

In [15]:
import numpy as np
py_list_2d = [[1, "A",2], [2, "B",2], [3, "C",2], [4, "D",2],
              [5, "E",2], [6, "F",2], [7, "G",2], [8, "H",2],
              [9, "I",2], [10, "J",2]]

np_array_2d = np.array(py_list_2d)  
#using python list to create a new numpy array

len(py_list_2d)

len(np_array_2d)
np_array_2d.shape #no () as shape is not function

(10, 3)

### 2.2 Arrays are fussy about type

In [16]:
#array converts everything to a single data type
py_list = [1, 1.5, 'A']
np.array(py_list)

#Remember (roughly speaking) an operation on a list works on the whole list. 
#In contrast, an operation on an array works on the individual elements of the array

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [21]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2 #combining the lists

np_array_1 + np_array_2 #adding the values correspondingly

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2 #doubling the size of the list

np_array*2 #multiplying the values

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list == 3  #regard this as an error?

np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [61]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function

np_array.sum()
np_array.mean()
np_array.max()
np_array.min()

15

## Exercise 1 :  Total recall?

1. Both are forms of data storage. Both are not in the form of key and values. Both can be in 2D?
2. Functions on lists acts on the entire list without affecting the values while function on arrays will act on each value of the array. Lists can accomodate multiple data types while array converts all values to a single data type.
3. Dictionary contains both a key and value. printing a key would give value as an output. removes the need to create two lists/arrays.


## Exercise 2 :  Index me

In [51]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


In [54]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
py_list[::2]

['a1', 'c3', 'e5', 'g7', 'i9']

## Exercise 3 :  Capitalise Heros

In [59]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()  
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()  
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [66]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]      
np_numbers = np.array(numbers)
onlyone = np_numbers == 1 

onlyone.sum()

9